spring.application.name=league-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:micropool}
spring.datasource.username=${DB_USER:sqd}
spring.datasource.password=${DB_PASSWORD:spud}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
